name: Getting Started

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Directory name-
          pwd
          echo Git version-
          git --version
  
      
